version: '3'
services:
  python3:
    build: .
    container_name: 'image-processing'
    stdin_open: true
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ${PWD}:/usr/src/app
    environment:
      - DISPLAY=${IP}:0
